[package]
name = "mimi"
version = "0.1.0"
authors = ["Сухарик <suhr@i2pmail.org>"]
edition = "2018"

[dependencies]
clap = "*"
portmidi = "*"

[dependencies.miosc]
git = "https://github.com/diaschisma/miosc.git"
